
services:
  nginx:
    build:
      context: ./nginx
    container_name: "nginx_cont"
    ports: 
      - "80:80"
    restart: always
    networks:
       - notes-app-nw
    depends_on:
       - django

  mysql:
    image: mysql
    container_name: "db_cont"
    ports: 
         - "3306:3306"
    networks:
      - notes-app-nw
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    healthcheck:
       test: ["CMD", "mysqladmin","ping","-h","localhost","-uroot","-proot"]
       interval: 10s
       timeout: 5s
       retries: 5
       start_period: 60s
    volumes:
      - ./data/mysql/db:/var/lib/mysql
      

  django:
    build:
      context: .
    container_name: "django_cont"
    ports:
      - "8000:8000"
    networks:
      - notes-app-nw
    restart: always
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    depends_on:
       mysql:
         condition: service_healthy
         restart: true
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    env_file:
      - ".env"

networks:
    notes-app-nw:
